import type { Metadata } from "next";
import { Inter, Lexend, Mona_Sans } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import NavBar from "@/components/nav-bar";

const lexend = Lexend({
	variable: "--font-lexend",
	subsets: ["latin"],
	display: "swap",
});

const monaSans = Mona_Sans({
	variable: "--font-mona",
	subsets: ["latin"],
	display: "swap",
});

const inter = Inter({
	variable: "--font-inter",
	subsets: ["latin"],
	display: "swap",
});

const avenirNext = localFont({
	variable: "--font-avenir-next",
	display: "swap",
	src: [
		{
			path: "./../fonts/avenir-next/AvenirNext-Regular-08.ttf",
			weight: "200",
			style: "normal",
		},
		{
			path: "./../fonts/avenir-next/AvenirNext-Medium-06.ttf",
			weight: "500",
			style: "normal",
		},
		{
			path: "./../fonts/avenir-next/AvenirNext-DemiBold-03.ttf",
			weight: "600",
			style: "normal",
		},
		{
			path: "./../fonts/avenir-next/AvenirNext-Regular-08.ttf",
			weight: "400",
			style: "normal",
		},
		{
			path: "./../fonts/avenir-next/AvenirNext-Bold-01.ttf",
			weight: "700",
			style: "normal",
		},
		{
			path: "./../fonts/avenir-next/AvenirNext-Heavy-09.ttf",
			weight: "800",
			style: "normal",
		},
	],
});

export const metadata: Metadata = {
	title: "Clusteer",
	description: "Generated by create next app",
};
export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${lexend.variable} ${monaSans.variable} ${inter.variable} ${avenirNext.variable} antialiased`}
			>
				<NavBar />
				{children}
			</body>
		</html>
	);
}
